spring:
    data:
      rest:
        base-path: /api
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username:
      password:
      driver-class-name: org.h2.Driver

---

spring:
    profiles: production
    data:
      rest:
        base-path: /api
    datasource:
      url: jdbc:mysql://localhost:3306/ifsulms?useSSL=false
      username: root
      password: toor
      driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      cache: false
    jpa:
      hibernate:
        ddl-auto: update
      
logging:
  level:
    org.springframework.security: DEBUG